### ISSUE TITLE
Cannot read property 'callee' of undefined

### ISSUE THREAD

**Issue by joliveros** [mchmielarski/babel-plugin-ng-annotate#5]
```
ERROR in ./client/app/components/newPersonalOrders/newPersonalOrders.controller.js
Module build failed: TypeError: /Users/chino/Documents/dsf/dsf.angular/client/app/components/newPersonalOrders/newPersonalOrders.controller.js: Cannot read property 'callee' of undefined
    at /Users/chino/Documents/dsf/dsf.angular/node_modules/babel-plugin-ng-annotate/lib/index.js:53:38
    at Array.forEach (native)
    at PluginPass.ClassDeclaration (/Users/chino/Documents/dsf/dsf.angular/node_modules/babel-plugin-ng-annotate/lib/index.js:45:17)
```

while using the following .babelrc and `"babel-plugin-ng-annotate": "^0.2.3",`:

```
{
  "plugins":[
    "add-module-exports",
    "ng-annotate",
    "syntax-decorators",
    "transform-node-env-inline",
    "transform-runtime"
  ],
  "presets":[
    "stage-0",
    "es2015"
  ]
}

```

any help would be appreciated.

Cheers

**Comment by zackschuster** [comment]
~~Based on my reading of the source, ng-annotate isn't detecting a decorator, so it skips building an array of injectables but doesn't bail out of execution. This causes the variable that eventually gets passed that array to remain undefined, resulting in a TypeError when the program tries to process it.~~ _Update_: Way off. The array is being built, but the node objects are returning undefined for some reason.

The problem could either be that you didn't inject properly (in which case make sure to do it exactly like [in the example](https://github.com/mchmielarski/babel-plugin-ng-annotate#how-to-use)) ~~or that `"syntax-decorators"` needs to be included before `"ng-annotate"` in .babelrc's plugins array.~~ _Update_: It doesn't.

**Comment by joliveros** [comment]
If I call any of the variables like $previousState in the constructor, I get that error. If I call them in another function outside of constructor. Then everything is good.

```
import {
    pick,
    isNumber
} from 'lodash';
import {
    isCreditCard
} from 'validator'
const DEBUG = require('../../common/Debug')('newPayment.controller');
const RECURRING_ORDERS_STATE = 'my-recurring-orders';
@Inject( //eslint-disable-line no-undef
    '$http',
    '$localStorage',
    '$location',
    '$previousState',
    '$scope',
    '$state',
    '$stateParams',
    '$timeout',
    'Hash',
    'Restangular',
    'toaster',
    'User'
)
class NewPaymentController {
    constructor(){
        this.init()
    }
    init(){
        let {
            $previousState,
            $scope,
            $location,
            User,
            Restangular
        } = this
        let userId = User.getUserId()
        let {
            defaultHeaders: RestangularHeaders
        } = this.Restangular

        Object.assign(this, {
            isCreditCard,
            isNumber,
            RestangularHeaders,
            userId
        })

```

**Comment by zackschuster** [comment]
How are you calling them? [This](http://www.es6fiddle.com/ij6bl8zm/) works fine for me ([output](http://i.imgur.com/3Pok7YW.png)). It might be a conflict with another plugin.

**Comment by joliveros** [comment]
now that you mention it. There is a conflict with one http://babeljs.io/docs/plugins/transform-decorators/. I configured babel to use the following (which was the only way I could get my project to build): 

```
{
  "plugins":[
    "add-module-exports",
    "ng-annotate",
    "syntax-decorators",
    "transform-class-constructor-call",
    "transform-class-properties",
    "transform-do-expressions",
    "transform-export-extensions",
    "transform-function-bind",
    "transform-node-env-inline",
    "transform-runtime"
  ],
  "presets":[
    "es2015",
    "stage-2"
  ]
}

```

**Comment by zackschuster** [comment]
So it works now?

**Comment by joliveros** [comment]
it works only if I don't use those variables in the constructor w/ the babelrc above

**Comment by zackschuster** [comment]
Hmm. I'd be curious to find out what specifically is causing the conflict. Do you have a git repo for your code I could play with?

**Comment by joliveros** [comment]
I need to put it together. I’ll post it here when it’s ready

-- 
jose oliveros
Sent with Airmail

On January 8, 2016 at 7:43:13 PM, Zack Schuster (notifications@github.com) wrote:

Hmm. I'd be curious to find out what specifically is causing the conflict. Do you have a git repo for your code I could play with?

**Comment by LostCrew** [comment]
@ledge23 @joliveros the same issue also occurs to me.
here is my piece of code:

``` js
@Inject('$scope', '$stateParams', '$timeout', 'Loadings', 'Alert', 'Countries', 'Communities', 'All')
class AddressFormController {
  constructor() {
    let countries = [];  // let | var | const all triggers the errors
  }
  // methods
}
```

`.babelrc`:

``` json
{
  "presets": ["es2015"],
  "plugins": [
    "syntax-decorators",
    "ng-annotate"
  ]
}
```

for completion, i'm using eslint with https://github.com/babel/eslint-plugin-babel and https://github.com/babel/babel-eslint.
let me know if you need more info.

**Comment by jmlopez-rod** [comment]
@mchmielarski Thanks for the merging the PR to fix this issue, will you be making a release to npm soon?

**Comment by mchmielarski** [comment]
It's done.
Sorry for delay.

**Comment by jmlopez-rod** [comment]
Thank you! :+1:
