### ISSUE TITLE
Cannot @Inject

### ISSUE THREAD

**Issue by evenfrost** [mchmielarski/babel-plugin-ng-annotate#9]
When I try to `@Inject` a service in my directive and recompile it, Babel throws `Decorators are not supported yet in 6.x pending proposal update.`. [The issue here.](http://phabricator.babeljs.io/T2645) My gulp Babel config is:

``` js
babel: {
  presets: ['es2015', 'stage-1'],
  plugins: ['syntax-decorators', 'ng-annotate'],
  babelrc: false,
},
```

At the other hand, when adding [decorators-legacy](https://github.com/loganfsmyth/babel-plugin-transform-decorators-legacy) plugin in Babel config, browser console throws an `Inject is not defined` error.

**Comment by evenfrost** [comment]
A temporary workaround is to remove `stage-1` preset and add all plugins [from this preset](http://babeljs.io/docs/plugins/preset-stage-1/) manually except for `transform-decorators`, though after doing so it won't be possible to use decorators stuff other than `@Inject`.

**Comment by mchmielarski** [comment]
hi,
I have just update dependencies and added .babelrc for /example
please, check it:

`cd example`
`babel src --out-dir lib`

**Comment by evenfrost** [comment]
All good now, thanks!
